# ------------------------------------------------------------------------------
# Kubernetes control-plane
# ------------------------------------------------------------------------------
kubernetes:
  apiServer:
    extraArgs:
      feature-gates: IPv6DualStack=true
      service-cluster-ip-range: 10.96.0.0/12,fd00:ffff::/112

  controllerManager:
    extraArgs:
      feature-gates: IPv6DualStack=true

  kubelet:
    config:
      featureGates:
        IPv6DualStack: true

  kubeProxy: 
    enabled: false
