{{- if .Values.tokenGenerator.enabled }}
{{- $fullName := include "ltsp.fullname" . -}}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: {{ $fullName }}-token-generator
  name: {{ $fullName }}-token-update
spec:
  schedule: "0 */12 * * *"
  jobTemplate:
    spec:
      template:
        {{- (include (print $.Template.BasePath "/token-generator-job.yaml") . | fromYaml ).spec.template | toYaml | nindent 8 }}
{{- end }}
